In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [17]:
a2 = np.array([[1, 2.0, 3.3], 
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
                [[10, 11, 12],
               [13, 14, 15], 
                [16, 17, 18]]])

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a3old = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])
a3old

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [31]:
a3old.shape

(3, 2, 3)

In [32]:
# ndim is number of dimensions
a1.ndim, a2.ndim, a3.ndim, a3old.ndim

(1, 2, 3, 3)

In [33]:
a1.dtype, a2.dtype, a3.dtype, a3old.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [34]:
a1.size, a2.size, a3.size, a3old.size

(3, 6, 18, 18)

In [36]:
type(a1), type(a2), type(a3), type(a3old)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [38]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [40]:
sample_array.dtype

dtype('int64')

In [41]:
ones = np.ones((2, 3))

In [42]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
ones.dtype

dtype('float64')

In [44]:
type(ones)

numpy.ndarray

In [45]:
zeros = np.zeros((2, 3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [48]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 4, 6, 2, 4],
       [3, 6, 1, 6, 2],
       [5, 8, 0, 3, 3]])

In [49]:
random_array.size

15

In [50]:
random_array.shape

(3, 5)

In [53]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.13187643, 0.11186128, 0.64803388],
       [0.39104492, 0.47649623, 0.91653678],
       [0.92954963, 0.06851269, 0.25096998],
       [0.28091553, 0.22030674, 0.15604854],
       [0.11595724, 0.03234677, 0.1608954 ]])

In [56]:
random_array_2.shape
# rows, columns

(5, 3)

In [57]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.48029429, 0.77683155, 0.79749095],
       [0.28189495, 0.50381268, 0.21029131],
       [0.58706733, 0.06115664, 0.8480312 ],
       [0.33145195, 0.68337853, 0.35043842],
       [0.44996073, 0.61796986, 0.64549328]])

In [58]:
# Pseudo-random numbers
np.random.seed()