In [1]:
import numpy as np

## DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [17]:
a2 = np.array([[1, 2.0, 3.3], 
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
                [[10, 11, 12],
               [13, 14, 15], 
                [16, 17, 18]]])

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [23]:
# ndim is number of dimensions
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [25]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [26]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5