In [1]:
import numpy as np

## 1. DataTypes & Attributes

In [3]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [17]:
a2 = np.array([[1, 2.0, 3.3], 
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
                [[10, 11, 12],
               [13, 14, 15], 
                [16, 17, 18]]])

In [18]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a3old = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])
a3old

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a3.shape

(2, 3, 3)

In [31]:
a3old.shape

(3, 2, 3)

In [32]:
# ndim is number of dimensions
a1.ndim, a2.ndim, a3.ndim, a3old.ndim

(1, 2, 3, 3)

In [33]:
a1.dtype, a2.dtype, a3.dtype, a3old.dtype

(dtype('int64'), dtype('float64'), dtype('int64'), dtype('int64'))

In [34]:
a1.size, a2.size, a3.size, a3old.size

(3, 6, 18, 18)

In [36]:
type(a1), type(a2), type(a3), type(a3old)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [27]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [38]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [40]:
sample_array.dtype

dtype('int64')

In [41]:
ones = np.ones((2, 3))

In [42]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [43]:
ones.dtype

dtype('float64')

In [44]:
type(ones)

numpy.ndarray

In [45]:
zeros = np.zeros((2, 3))

In [46]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [48]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 4, 6, 2, 4],
       [3, 6, 1, 6, 2],
       [5, 8, 0, 3, 3]])

In [49]:
random_array.size

15

In [50]:
random_array.shape

(3, 5)

In [53]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.13187643, 0.11186128, 0.64803388],
       [0.39104492, 0.47649623, 0.91653678],
       [0.92954963, 0.06851269, 0.25096998],
       [0.28091553, 0.22030674, 0.15604854],
       [0.11595724, 0.03234677, 0.1608954 ]])

In [56]:
random_array_2.shape
# rows, columns

(5, 3)

In [57]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.48029429, 0.77683155, 0.79749095],
       [0.28189495, 0.50381268, 0.21029131],
       [0.58706733, 0.06115664, 0.8480312 ],
       [0.33145195, 0.68337853, 0.35043842],
       [0.44996073, 0.61796986, 0.64549328]])

In [74]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [71]:
random_array_4.shape

(5, 3)

In [76]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [77]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

## 3. Viewing arrays and matrices

In [78]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [79]:
a1

array([1, 2, 3])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [81]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [82]:
a1[0]

1

In [83]:
a2[0]

array([1. , 2. , 3.3])

In [84]:
a2.shape

(2, 3)

In [85]:
a3.shape

(2, 3, 3)

In [86]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [88]:
a2[1]

array([4. , 5. , 6.5])

In [89]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [95]:
a3[:1, :1]

array([[[1, 2, 3]]])

In [96]:
a3[:1, :1, :1]

array([[[1]]])

In [97]:
a3[0, :2, :2]

array([[1, 2],
       [4, 5]])

In [98]:
a3.shape

(2, 3, 3)

In [100]:
a3[:1, :2]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [101]:
a3[:1, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [109]:
# last column in first row
a3[:1, :3, 2:]

array([[[3],
        [6],
        [9]]])

In [112]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1],
         [4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0]],

        [[0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0],
         [8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3]],

        [[9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1],
         [0, 1, 0, 1, 8],
         [4, 1, 6, 8, 5]]],


       [[[2, 4, 7, 4, 1],
         [2, 8, 5, 2, 9],
         [6, 2, 5, 7, 7],
         [5, 5, 6, 0, 6]],

        [[4, 6, 2, 6, 8],
         [7, 0, 5, 8, 9],
         [7, 7, 6, 2, 5],
         [6, 1, 9, 3, 4]],

        [[0, 3, 5, 6, 4],
         [0, 4, 1, 5, 2],
         [4, 8, 7, 5, 7],
         [5, 3, 7, 6, 2]]]])

In [113]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [147]:
a4[1:, :1, :1]

array([[[[2, 4, 7, 4, 1]]]])

In [150]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :1]

array([[[[1],
         [0],
         [4],
         [1]],

        [[0],
         [5],
         [8],
         [0]],

        [[9],
         [0],
         [0],
         [4]]],


       [[[2],
         [2],
         [6],
         [5]],

        [[4],
         [7],
         [7],
         [6]],

        [[0],
         [0],
         [4],
         [5]]]])

## 4. Manipulating & Comparing Arrays

### Arithmetic 

In [151]:
a1

array([1, 2, 3])

In [153]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [154]:
a1 + ones

array([2., 3., 4.])

In [155]:
a1 - ones

array([0., 1., 2.])

In [156]:
a1 * ones

array([1., 2., 3.])

In [159]:
a1

array([1, 2, 3])

In [157]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [158]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [160]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [163]:
a1 / ones

array([1., 2., 3.])

In [165]:
a2 /a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [166]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [167]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [168]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [169]:
np.add(a1, ones)

array([2., 3., 4.])

In [172]:
a1 + ones

array([2., 3., 4.])

In [171]:
a1 % 2

array([1, 0, 1])

In [173]:
a2 % 2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [174]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [175]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
(The formation of things into a cluster)
Aggregation = performing the same operation on a number of things

In [176]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [177]:
sum(listy_list)

6

In [178]:
a1

array([1, 2, 3])

In [179]:
type(a1)

numpy.ndarray

In [180]:
sum(a1)

6

In [181]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use 
NumPy's methods on NumPy arrays (`np.sum()`).

In [184]:
# Create a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [185]:
massive_array[:10]

array([0.80510153, 0.39294502, 0.52251073, 0.67854101, 0.18845405,
       0.33150603, 0.22394903, 0.75098623, 0.50255376, 0.14066532])

In [186]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

5.83 ms ± 135 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
28.2 µs ± 1.44 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [187]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [188]:
np.mean(a2)

3.6333333333333333

In [189]:
np.max(a2)

6.5

In [190]:
np.min(a2)

1.0

In [194]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [193]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [196]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422